set(fixture_dir "${CMAKE_CURRENT_LIST_DIR}/../fixtures")
file(READ "${fixture_dir}/directory-corpus.json" manifest)
string(JSON expected_archive_hash GET "${manifest}" archive_sha256)
file(SHA256 "${fixture_dir}/directory-corpus.zip" archive_hash)
if(NOT archive_hash STREQUAL expected_archive_hash)
    message(FATAL_ERROR "目录素材 ZIP 哈希不匹配")
endif()

string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef run_id)
set(run_root "${TEST_DIR}/run-${run_id}")
if(EXISTS "${run_root}")
    message(FATAL_ERROR "测试目录已存在：${run_root}")
endif()
set(source "${run_root}/素材 原始 🔐")
file(MAKE_DIRECTORY "${source}")
file(ARCHIVE_EXTRACT INPUT "${fixture_dir}/directory-corpus.zip" DESTINATION "${source}")
file(WRITE "${run_root}/encrypt-password.txt" "corpus password\ncorpus password\n")
file(WRITE "${run_root}/decrypt-password.txt" "corpus password\n")
file(WRITE "${run_root}/wrong-password.txt" "wrong\n")

function(verify_tree root)
    set(expected_paths)
    string(JSON directory_count LENGTH "${manifest}" directories)
    math(EXPR last_directory "${directory_count} - 1")
    foreach(i RANGE 0 ${last_directory})
        string(JSON path GET "${manifest}" directories ${i})
        if(NOT IS_DIRECTORY "${root}/${path}" OR IS_SYMLINK "${root}/${path}")
            message(FATAL_ERROR "素材目录缺失或类型错误：${root}/${path}")
        endif()
        list(APPEND expected_paths "${path}")
    endforeach()
    string(JSON file_count LENGTH "${manifest}" files)
    math(EXPR last_file "${file_count} - 1")
    foreach(i RANGE 0 ${last_file})
        string(JSON path GET "${manifest}" files ${i} path)
        string(JSON expected_size GET "${manifest}" files ${i} size_bytes)
        string(JSON expected_hash GET "${manifest}" files ${i} sha256)
        if(NOT EXISTS "${root}/${path}" OR IS_DIRECTORY "${root}/${path}" OR IS_SYMLINK "${root}/${path}")
            message(FATAL_ERROR "素材文件缺失或类型错误：${root}/${path}")
        endif()
        file(SIZE "${root}/${path}" actual_size)
        file(SHA256 "${root}/${path}" actual_hash)
        if(NOT actual_size EQUAL expected_size OR NOT actual_hash STREQUAL expected_hash)
            message(FATAL_ERROR "素材文件大小或 SHA-256 不匹配：${root}/${path}")
        endif()
        list(APPEND expected_paths "${path}")
    endforeach()
    file(GLOB_RECURSE actual_paths LIST_DIRECTORIES TRUE RELATIVE "${root}" "${root}/*")
    list(SORT actual_paths)
    list(SORT expected_paths)
    if(NOT "${actual_paths}" STREQUAL "${expected_paths}")
        message(FATAL_ERROR "素材目录条目集合不匹配：${root}")
    endif()
endfunction()

function(run password expected)
    execute_process(COMMAND "${FILECRYPT}" ${ARGN}
        WORKING_DIRECTORY "${run_root}" INPUT_FILE "${run_root}/${password}-password.txt"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error ENCODING UTF-8)
    if(NOT "${result}" MATCHES "^[0-9]+$")
        message(FATAL_ERROR "素材命令无法正常执行：${ARGN}\n${result}\n${error}")
    endif()
    if((expected AND NOT result EQUAL 0) OR (NOT expected AND result EQUAL 0))
        message(FATAL_ERROR "素材命令结果错误：${ARGN}\n退出结果：${result}\n${output}\n${error}")
    endif()
    file(GLOB temporary "${run_root}/.filecrypt-*")
    if(temporary)
        message(FATAL_ERROR "素材命令遗留临时输出：${temporary}")
    endif()
endfunction()

verify_tree("${source}")
foreach(algorithm IN ITEMS aes xchacha)
    foreach(compressed IN ITEMS no-compress compress)
        set(encrypted "${run_root}/${algorithm}-${compressed}.fcry")
        set(restored "${run_root}/恢复 🔓-${algorithm}-${compressed}")
        run(encrypt TRUE -e "${source}" "${encrypted}" -a "${algorithm}" "${compressed}"
            memory-kib 8192 iterations 1 parallelism 1)
        run(wrong FALSE -d "${encrypted}" "${restored}")
        if(EXISTS "${restored}")
            message(FATAL_ERROR "错误密码发布了素材恢复目录：${restored}")
        endif()
        run(decrypt TRUE -d "${encrypted}" "${restored}")
        verify_tree("${restored}")
    endforeach()
endforeach()
verify_tree("${source}")
file(REMOVE_RECURSE "${run_root}")
if(EXISTS "${run_root}")
    message(FATAL_ERROR "无法清理本轮素材测试目录：${run_root}")
endif()
