file(MAKE_DIRECTORY "${TEST_DIR}")
# 测试专用非敏感密码只写入已忽略的构建目录，不通过命令行传递。
file(WRITE "${TEST_DIR}/encrypt-password.txt" "test password \ntest password \n")
file(WRITE "${TEST_DIR}/decrypt-password.txt" "test password \n")
file(WRITE "${TEST_DIR}/wrong-password.txt" "wrong password\n")
file(WRITE "${TEST_DIR}/mismatch-password.txt" "test password \ndifferent\n")
file(WRITE "${TEST_DIR}/missing-confirmation.txt" "test password \n")
file(WRITE "${TEST_DIR}/empty-password.txt" "\n\n")
file(WRITE "${TEST_DIR}/input file.bin" "UTF-8 content: 中文\nline two\n")

# 使用固定非敏感管道输入执行 CLI 并验证成功状态。
function(run_success password_file)
    execute_process(COMMAND "${FILECRYPT}" ${ARGN}
        WORKING_DIRECTORY "${TEST_DIR}"
        INPUT_FILE "${TEST_DIR}/${password_file}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error ENCODING UTF-8)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "文件命令失败：${ARGN}\n${error}")
    endif()
    set(last_output "${output}" PARENT_SCOPE)
endfunction()

# 要求失败且不发布任何输出文件。
function(run_failure password_file destination)
    file(REMOVE "${destination}")
    execute_process(COMMAND "${FILECRYPT}" ${ARGN}
        INPUT_FILE "${TEST_DIR}/${password_file}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error ENCODING UTF-8)
    if(result EQUAL 0 OR EXISTS "${destination}")
        message(FATAL_ERROR "失败命令发布了输出：${ARGN}")
    endif()
    file(GLOB temporary_files "${TEST_DIR}/.filecrypt-*.tmp")
    if(temporary_files)
        message(FATAL_ERROR "失败命令遗留临时输出：${ARGN}\n${error}\n${temporary_files}")
    endif()
    set(last_error "${error}" PARENT_SCOPE)
endfunction()

# 验证选项在读取密码前就被拒绝，并报告明确原因。
function(expect_option_error expected)
    run_failure(empty-password.txt "${TEST_DIR}/parse-error.fcry"
        -e "${source}" "${TEST_DIR}/parse-error.fcry" ${ARGN})
    string(FIND "${last_error}" "${expected}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "选项错误提示不匹配：${ARGN}\n${last_error}")
    endif()
endfunction()

set(source "${TEST_DIR}/input file.bin")
set(restored "${TEST_DIR}/restored file.bin")
foreach(algorithm IN ITEMS aes xchacha aes-256-gcm xchacha20-poly1305)
    set(encrypted "${TEST_DIR}/${algorithm}.fcry")
    file(REMOVE "${encrypted}" "${restored}")
    if(algorithm STREQUAL "aes" OR algorithm STREQUAL "xchacha")
        set(encrypt_command -e)
        set(decrypt_command -d)
        set(algorithm_option -a)
    else()
        set(encrypt_command encrypt)
        set(decrypt_command decrypt)
        set(algorithm_option algorithm)
    endif()
    run_success(encrypt-password.txt ${encrypt_command} "${source}" "${encrypted}" ${algorithm_option} "${algorithm}"
        memory-kib 8192 iterations 1 parallelism 1)
    if(NOT last_output MATCHES "加密完成" OR NOT last_output MATCHES "忘记密码")
        message(FATAL_ERROR "加密完成提示不完整")
    endif()
    run_success(decrypt-password.txt ${decrypt_command} "${encrypted}" "${restored}")
    if(NOT last_output MATCHES "认证通过")
        message(FATAL_ERROR "解密未报告认证通过")
    endif()
    file(SHA256 "${source}" source_hash)
    file(SHA256 "${restored}" restored_hash)
    if(NOT source_hash STREQUAL restored_hash)
        message(FATAL_ERROR "CLI 文件往返不一致")
    endif()
    run_failure(wrong-password.txt "${TEST_DIR}/wrong.bin" decrypt "${encrypted}" "${TEST_DIR}/wrong.bin")
    run_failure(decrypt-password.txt "${TEST_DIR}/limited.bin" decrypt "${encrypted}"
        "${TEST_DIR}/limited.bin" max-memory-kib 4096)
    # 已有输出失败时必须保持内容不变。
    execute_process(COMMAND "${FILECRYPT}" decrypt "${encrypted}" "${restored}"
        INPUT_FILE "${TEST_DIR}/decrypt-password.txt" RESULT_VARIABLE result)
    file(SHA256 "${restored}" after_hash)
    if(result EQUAL 0 OR NOT restored_hash STREQUAL after_hash)
        message(FATAL_ERROR "已有明文被覆盖")
    endif()
endforeach()

run_failure(mismatch-password.txt "${TEST_DIR}/mismatch.fcry" encrypt "${source}" "${TEST_DIR}/mismatch.fcry")
run_failure(missing-confirmation.txt "${TEST_DIR}/missing.fcry" encrypt "${source}" "${TEST_DIR}/missing.fcry")
run_failure(empty-password.txt "${TEST_DIR}/empty.fcry" encrypt "${source}" "${TEST_DIR}/empty.fcry")
run_failure(encrypt-password.txt "${TEST_DIR}/invalid.fcry" encrypt "${source}" "${TEST_DIR}/invalid.fcry"
    memory-kib 0)

# 同一选项的不同写法也必须判为重复，开关冲突不能靠顺序覆盖。
expect_option_error("选项重复或冲突" algorithm aes -a xchacha)
expect_option_error("选项重复或冲突" compress no-compress)
expect_option_error("选项重复或冲突" -z compress)
expect_option_error("选项重复或冲突" no-compress no-compress)
expect_option_error("选项重复或冲突" memory-kib 8192 memory-kib 16384)
expect_option_error("选项重复或冲突" max-iterations 2 max-iterations 3)
expect_option_error("选项缺少值" -a)
expect_option_error("选项缺少值" iterations)
expect_option_error("不支持的算法名称" -a unknown)
expect_option_error("未知或不适用于当前命令" --algorithm aes)
expect_option_error("未知或不适用于当前命令" a aes)
expect_option_error("未知或不适用于当前命令" max-output-bytes 1024)
foreach(value IN ITEMS 0 -1 1x 4294967296)
    expect_option_error("参数必须是正的 32 位整数" memory-kib "${value}")
endforeach()
run_failure(decrypt-password.txt "${TEST_DIR}/parse-decrypt.bin" -d "${encrypted}"
    "${TEST_DIR}/parse-decrypt.bin" -a aes)
if(NOT last_error MATCHES "未知或不适用于当前命令")
    message(FATAL_ERROR "解密不应接受算法覆盖：${last_error}")
endif()

# 固定路径位置使选项同名或横线开头的文件名仍按路径解释。
foreach(pair IN ITEMS "algorithm,compress" "-a,-z")
    string(REPLACE "," ";" names "${pair}")
    list(GET names 0 input_name)
    list(GET names 1 output_name)
    file(COPY_FILE "${source}" "${TEST_DIR}/${input_name}")
    file(REMOVE "${TEST_DIR}/${output_name}" "${restored}")
    run_success(encrypt-password.txt -e "${input_name}" "${output_name}"
        algorithm xchacha no-compress memory-kib 8192 iterations 1 parallelism 1)
    run_success(decrypt-password.txt -i "${output_name}")
    if(NOT last_output MATCHES "XChaCha20-Poly1305" OR NOT last_output MATCHES "压缩：否")
        message(FATAL_ERROR "混合写法生成的文件属性错误")
    endif()
    run_success(decrypt-password.txt -d "${output_name}" "${restored}")
    file(SHA256 "${restored}" reserved_hash)
    if(NOT reserved_hash STREQUAL source_hash)
        message(FATAL_ERROR "固定位置路径往返失败：${pair}")
    endif()
endforeach()

# 压缩长短写法均执行真实加解密，解压选项仅影响运行策略。
foreach(algorithm IN ITEMS aes xchacha)
    set(encrypted "${TEST_DIR}/${algorithm}-compressed.fcry")
    file(REMOVE "${encrypted}" "${restored}")
    if(algorithm STREQUAL "aes")
        set(compression_option compress)
    else()
        set(compression_option -z)
    endif()
    run_success(encrypt-password.txt -e "${source}" "${encrypted}" -a "${algorithm}" ${compression_option}
        memory-kib 8192 iterations 1 parallelism 1)
    run_success(decrypt-password.txt -i "${encrypted}")
    if(NOT last_output MATCHES "压缩：是" OR NOT last_output MATCHES "Zstandard")
        message(FATAL_ERROR "压缩文件信息不完整")
    endif()
    run_failure(decrypt-password.txt "${restored}" -d "${encrypted}" "${restored}" max-output-bytes 1)
    run_failure(wrong-password.txt "${restored}" -d "${encrypted}" "${restored}")
    run_success(decrypt-password.txt -d "${encrypted}" "${restored}"
        max-output-bytes 10737418240 max-window-kib 65536)
    file(SHA256 "${restored}" compressed_hash)
    if(NOT compressed_hash STREQUAL source_hash)
        message(FATAL_ERROR "压缩 CLI 往返失败")
    endif()
endforeach()
foreach(value IN ITEMS 0 3 2097152)
    run_failure(empty-password.txt "${TEST_DIR}/invalid-window.bin" -d "${encrypted}"
        "${TEST_DIR}/invalid-window.bin" max-window-kib "${value}")
    if(last_error MATCHES "密码不能为空")
        message(FATAL_ERROR "窗口参数未在读取密码前校验")
    endif()
endforeach()
foreach(value IN ITEMS 0 -1 1x 18446744073709551616)
    run_failure(empty-password.txt "${TEST_DIR}/invalid-output.bin" -d "${encrypted}"
        "${TEST_DIR}/invalid-output.bin" max-output-bytes "${value}")
    if(NOT last_error MATCHES "解压输出上限必须是正的 64 位整数")
        message(FATAL_ERROR "解压输出上限参数提示不正确")
    endif()
endforeach()

# 默认 KDF 配置也必须可创建并由读取端重建。
set(default_file "${TEST_DIR}/default.fcry")
file(REMOVE "${default_file}" "${restored}")
run_success(encrypt-password.txt encrypt "${source}" "${default_file}")
run_success(decrypt-password.txt decrypt "${default_file}" "${restored}")
file(SHA256 "${restored}" restored_hash)
if(NOT restored_hash STREQUAL source_hash)
    message(FATAL_ERROR "默认参数文件往返失败")
endif()
file(GLOB temporary_files "${TEST_DIR}/.filecrypt-*.tmp")
if(temporary_files)
    message(FATAL_ERROR "CLI 遗留临时输出：${temporary_files}")
endif()
