set(TEST_DIR "${TEST_DIR}/目录 空格 🔐")
if(WIN32)
    foreach(junction IN ITEMS "${TEST_DIR}/junction" "${TEST_DIR}/source/junction")
        if(EXISTS "${junction}")
            execute_process(COMMAND "${CLEANUP_TOOL}" --remove-junction "${junction}" RESULT_VARIABLE removed)
            if(NOT removed EQUAL 0)
                message(FATAL_ERROR "Cannot remove test junction safely")
            endif()
        endif()
    endforeach()
endif()
file(MAKE_DIRECTORY "${TEST_DIR}/source/sub/empty" "${TEST_DIR}/source/empty" "${TEST_DIR}/empty-source")
file(WRITE "${TEST_DIR}/source/中文 🔑.txt" "directory contents\n")
file(WRITE "${TEST_DIR}/source/sub/zero" "")
string(REPEAT "streaming data\n" 10000 data)
file(WRITE "${TEST_DIR}/source/sub/data.bin" "${data}")
file(WRITE "${TEST_DIR}/encrypt-password.txt" "directory password\ndirectory password\n")
file(WRITE "${TEST_DIR}/decrypt-password.txt" "directory password\n")
file(WRITE "${TEST_DIR}/wrong-password.txt" "wrong\n")

function(run password expected)
    execute_process(COMMAND "${FILECRYPT}" ${ARGN}
        WORKING_DIRECTORY "${TEST_DIR}" INPUT_FILE "${TEST_DIR}/${password}-password.txt"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error ENCODING UTF-8)
    if(expected AND NOT result EQUAL 0)
        message(FATAL_ERROR "目录命令失败：${ARGN}\n${error}")
    elseif(NOT expected AND result EQUAL 0)
        message(FATAL_ERROR "非法目录操作未拒绝：${ARGN}")
    endif()
    file(GLOB temporary "${TEST_DIR}/.filecrypt-*")
    if(temporary)
        message(FATAL_ERROR "目录命令遗留临时输出：${temporary}\n${error}")
    endif()
    set(last_output "${output}" PARENT_SCOPE)
endfunction()

foreach(algorithm IN ITEMS aes xchacha)
    foreach(compressed IN ITEMS no-compress compress)
        set(encrypted "${algorithm}-${compressed}.fcry")
        set(output "${TEST_DIR}/恢复 🔓-${algorithm}-${compressed}")
        file(REMOVE "${TEST_DIR}/${encrypted}")
        # 本测试仅清理固定测试目录中的自身恢复目标，允许重复执行。
        file(REMOVE_RECURSE "${output}")
        run(encrypt TRUE -e source "${algorithm}-${compressed}" -a "${algorithm}" "${compressed}"
            memory-kib 8192 iterations 1 parallelism 1)
        run(decrypt TRUE -i "${encrypted}")
        if(NOT last_output MATCHES "目录：是" OR NOT last_output MATCHES "文件类型：N/A")
            message(FATAL_ERROR "目录信息不正确：${last_output}")
        endif()
        run(wrong FALSE -d "${encrypted}" "${output}")
        run(decrypt FALSE -d "${encrypted}" "${output}" max-entries 1)
        run(decrypt FALSE -d "${encrypted}" "${output}" max-index-bytes 1)
        run(decrypt FALSE -d "${encrypted}" "${output}" max-name-bytes 1)
        run(decrypt FALSE -d "${encrypted}" "${output}" max-depth 1)
        run(decrypt FALSE -d "${encrypted}" "${output}" max-output-bytes 1)
        run(decrypt FALSE -d "${encrypted}" "${output}" max-archive-bytes 1)
        if(EXISTS "${output}")
            message(FATAL_ERROR "失败操作发布了目录")
        endif()
        run(decrypt TRUE -d "${encrypted}" "${output}")
        foreach(path IN ITEMS "中文 🔑.txt" sub/zero sub/data.bin)
            file(SHA256 "${TEST_DIR}/source/${path}" before)
            file(SHA256 "${output}/${path}" after)
            if(NOT before STREQUAL after)
                message(FATAL_ERROR "目录文件内容不一致：${path}")
            endif()
        endforeach()
        if(NOT IS_DIRECTORY "${output}/empty" OR NOT IS_DIRECTORY "${output}/sub/empty" OR EXISTS "${output}/source")
            message(FATAL_ERROR "目录结构或空目录恢复错误")
        endif()
        run(decrypt FALSE -d "${encrypted}" "${output}")
        file(SHA256 "${output}/sub/data.bin" after_conflict)
        file(SHA256 "${TEST_DIR}/source/sub/data.bin" original)
        if(NOT original STREQUAL after_conflict)
            message(FATAL_ERROR "已有目录被更改")
        endif()
    endforeach()
endforeach()

file(REMOVE "${TEST_DIR}/empty.fcry")
file(REMOVE_RECURSE "${TEST_DIR}/empty-restored")
run(encrypt TRUE encrypt empty-source empty -z memory-kib 8192 iterations 1 parallelism 1)
run(decrypt TRUE decrypt empty empty-restored)
file(GLOB empty_contents "${TEST_DIR}/empty-restored/*")
if(NOT IS_DIRECTORY "${TEST_DIR}/empty-restored" OR empty_contents)
    message(FATAL_ERROR "空目录恢复失败")
endif()
file(REMOVE_RECURSE "${TEST_DIR}/trailing-restored")
run(decrypt TRUE decrypt empty "trailing-restored/")
if(NOT IS_DIRECTORY "${TEST_DIR}/trailing-restored")
    message(FATAL_ERROR "带末尾分隔符的目录目标恢复失败")
endif()
run(encrypt FALSE encrypt source source/inside memory-kib 8192 iterations 1 parallelism 1)
if(EXISTS "${TEST_DIR}/source/inside.fcry")
    message(FATAL_ERROR "目录内输出未拒绝")
endif()
run(encrypt FALSE encrypt source limited max-entries 1 memory-kib 8192 iterations 1 parallelism 1)
if(EXISTS "${TEST_DIR}/limited.fcry")
    message(FATAL_ERROR "扫描限制失败仍发布了密文")
endif()

if(WIN32)
    # junction 不需要符号链接权限，验证根和树内 reparse point 都明确失败。
    if(NOT EXISTS "${TEST_DIR}/junction")
        execute_process(COMMAND cmd /c mklink /J "${TEST_DIR}/junction" "${TEST_DIR}/source"
            RESULT_VARIABLE linked OUTPUT_QUIET ERROR_QUIET)
        if(NOT linked EQUAL 0)
            message(FATAL_ERROR "Cannot create junction fixture")
        endif()
    endif()
    run(encrypt FALSE encrypt junction junction-output memory-kib 8192 iterations 1 parallelism 1)
    # 词法消去 .. 之前也必须拒绝路径中的 junction。
    file(REMOVE "${TEST_DIR}/cancelled-link.fcry")
    run(encrypt FALSE encrypt junction/../empty-source cancelled-link memory-kib 8192 iterations 1 parallelism 1)
    if(NOT EXISTS "${TEST_DIR}/source/junction")
        execute_process(COMMAND cmd /c mklink /J "${TEST_DIR}/source/junction" "${TEST_DIR}/empty-source"
            RESULT_VARIABLE linked OUTPUT_QUIET ERROR_QUIET)
        if(NOT linked EQUAL 0)
            message(FATAL_ERROR "Cannot create nested junction fixture")
        endif()
    endif()
    run(encrypt FALSE encrypt source junction-output memory-kib 8192 iterations 1 parallelism 1)
    # 原生 helper 核对 junction 类型及名称，只删除链接，不遍历其目标。
    foreach(junction IN ITEMS "${TEST_DIR}/junction" "${TEST_DIR}/source/junction")
        execute_process(COMMAND "${CLEANUP_TOOL}" --remove-junction "${junction}" RESULT_VARIABLE removed)
        if(NOT removed EQUAL 0)
            message(FATAL_ERROR "Cannot remove test junction safely")
        endif()
    endforeach()
endif()
