# 同时覆盖 Unicode 父目录、空格和补充平面字符；Windows 不应依赖 ANSI 代码页。
set(TEST_DIR "${TEST_DIR}/中文 路径 🔐")
file(MAKE_DIRECTORY "${TEST_DIR}")

# 执行命令并要求其成功，返回输出供断言使用。
function(run_success output_name)
    execute_process(COMMAND "${FILECRYPT}" ${ARGN}
        WORKING_DIRECTORY "${TEST_DIR}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error ENCODING UTF-8)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "命令失败：${ARGN}\n${error}")
    endif()
    set(${output_name} "${output}" PARENT_SCOPE)
endfunction()

# 验证文件信息包含指定的中文字段和值。
function(expect_text output text)
    string(FIND "${output}" "${text}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "输出缺少 ${text}：\n${output}")
    endif()
endfunction()

# 执行非法操作并要求返回非零退出码。
function(run_failure)
    execute_process(COMMAND "${FILECRYPT}" ${ARGN}
        WORKING_DIRECTORY "${TEST_DIR}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error ENCODING UTF-8)
    if(result EQUAL 0)
        message(FATAL_ERROR "非法操作未被拒绝：${ARGN}")
    endif()
    set(last_error "${error}" PARENT_SCOPE)
endfunction()

run_success(help_long help)
run_success(help_short -h)
if(NOT help_long STREQUAL help_short)
    message(FATAL_ERROR "完整与简写帮助不一致")
endif()
expect_text("${help_short}" "前两个参数固定为输入、输出路径")
run_failure(--help)
run_failure(e input output)
run_failure(--encrypt input output)

foreach(algorithm IN ITEMS aes xchacha aes-256-gcm xchacha20-poly1305)
    foreach(directory IN ITEMS OFF ON)
        foreach(compressed IN ITEMS OFF ON)
            set(path "${TEST_DIR}/${algorithm}-${directory}-${compressed}.fcry")
            # 仅清理由本测试拥有的单个样本，允许重复运行。
            file(REMOVE "${path}")
            set(options algorithm "${algorithm}")
            if(directory)
                list(APPEND options directory)
            endif()
            if(compressed)
                list(APPEND options compress)
            endif()
            run_success(generated sample "${path}" ${options})
            expect_text("${generated}" "未执行加密")
            run_success(info -i "${path}")
            if(algorithm STREQUAL "aes" OR algorithm STREQUAL "aes-256-gcm")
                expect_text("${info}" "加密算法：AES-256-GCM")
            else()
                expect_text("${info}" "加密算法：XChaCha20-Poly1305")
            endif()
            if(directory)
                expect_text("${info}" "目录：是")
                expect_text("${info}" "目录索引长度：0 字节")
            else()
                expect_text("${info}" "目录：否")
            endif()
            if(compressed)
                expect_text("${info}" "压缩：是")
                expect_text("${info}" "压缩算法：Zstandard")
            else()
                expect_text("${info}" "压缩：否")
            endif()
            expect_text("${info}" "认证状态：未验证")
            file(SHA256 "${path}" before)
            run_failure(sample "${path}" ${options})
            file(SHA256 "${path}" after)
            if(NOT before STREQUAL after)
                message(FATAL_ERROR "已有文件被覆盖")
            endif()
        endforeach()
    endforeach()
endforeach()

file(WRITE "${TEST_DIR}/invalid.fcry" "FCRX")
run_failure(info "${TEST_DIR}/invalid.fcry")
file(WRITE "${TEST_DIR}/unknown-version.fcry" "FCRY22")
execute_process(COMMAND "${FILECRYPT}" info "${TEST_DIR}/unknown-version.fcry"
    RESULT_VARIABLE result ERROR_VARIABLE error ENCODING UTF-8)
if(result EQUAL 0 OR NOT error MATCHES "Unsupported FileCrypt version")
    message(FATAL_ERROR "未知版本未在前缀分发阶段拒绝：${error}")
endif()
string(REPEAT "x" 124 invalid_tail)
file(WRITE "${TEST_DIR}/invalid.fcry" "FCRX${invalid_tail}")
run_failure(info "${TEST_DIR}/invalid.fcry")
run_failure(info "${TEST_DIR}/missing.fcry")
run_failure(sample "${TEST_DIR}/bad-option.fcry" algorithm unsupported)
if(EXISTS "${TEST_DIR}/bad-option.fcry")
    message(FATAL_ERROR "非法选项创建了文件")
endif()
run_failure(sample "${TEST_DIR}/bad-option.fcry" algorithm aes -a xchacha)
expect_text("${last_error}" "选项重复或冲突")
run_failure(sample "${TEST_DIR}/bad-option.fcry" compress no-compress)
expect_text("${last_error}" "选项重复或冲突")
run_failure(sample "${TEST_DIR}/bad-option.fcry" -a)
expect_text("${last_error}" "选项缺少值")
file(REMOVE "${TEST_DIR}/short-sample.fcry")
run_success(sample_short sample "${TEST_DIR}/short-sample.fcry" -a xchacha directory -z)
run_success(sample_info -i "${TEST_DIR}/short-sample.fcry")
expect_text("${sample_info}" "目录：是")
expect_text("${sample_info}" "压缩：是")
file(REMOVE "${TEST_DIR}/no-compress.fcry")
run_success(sample_plain sample "${TEST_DIR}/no-compress.fcry" no-compress)
run_success(sample_info info "${TEST_DIR}/no-compress.fcry")
expect_text("${sample_info}" "压缩：否")

# info 只解释公开前缀，载荷的存在不代表认证成功。
file(APPEND "${path}" "payload")
run_success(info info "${path}")
expect_text("${info}" "载荷：存在")
expect_text("${info}" "认证状态：未验证")

# sample/info 的文件名和未知选项诊断都必须原样输出 UTF-8。
set(unicode_name "格式 示例 🔑.fcry")
file(REMOVE "${TEST_DIR}/${unicode_name}")
run_success(generated sample "${unicode_name}" -a xchacha -z)
expect_text("${generated}" "${unicode_name}")
run_success(info info "${TEST_DIR}/${unicode_name}")
expect_text("${info}" "加密文件名：${unicode_name}")
run_failure(sample "${TEST_DIR}/bad-option.fcry" "未知选项 🔑")
expect_text("${last_error}" "未知选项：未知选项 🔑")
