file(MAKE_DIRECTORY "${TEST_DIR}")

# 执行命令并要求其成功，返回输出供断言使用。
function(run_success output_name)
    execute_process(COMMAND "${FILECRYPT}" ${ARGN}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error ENCODING UTF-8)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "命令失败：${ARGN}\n${error}")
    endif()
    set(${output_name} "${output}" PARENT_SCOPE)
endfunction()

# 验证文件信息包含指定的中文字段和值。
function(expect_text output text)
    string(FIND "${output}" "${text}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "输出缺少 ${text}：\n${output}")
    endif()
endfunction()

# 执行非法操作并要求返回非零退出码。
function(run_failure)
    execute_process(COMMAND "${FILECRYPT}" ${ARGN}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error ENCODING UTF-8)
    if(result EQUAL 0)
        message(FATAL_ERROR "非法操作未被拒绝：${ARGN}")
    endif()
endfunction()

foreach(algorithm IN ITEMS aes-256-gcm xchacha20-poly1305)
    foreach(directory IN ITEMS OFF ON)
        foreach(compressed IN ITEMS OFF ON)
            set(path "${TEST_DIR}/${algorithm}-${directory}-${compressed}.fcry")
            # 仅清理由本测试拥有的单个样本，允许重复运行。
            file(REMOVE "${path}")
            set(options --algorithm "${algorithm}")
            if(directory)
                list(APPEND options --directory)
            endif()
            if(compressed)
                list(APPEND options --compressed)
            endif()
            run_success(generated sample "${path}" ${options})
            expect_text("${generated}" "未执行加密")
            run_success(info info "${path}")
            if(algorithm STREQUAL "aes-256-gcm")
                expect_text("${info}" "加密算法：AES-256-GCM")
            else()
                expect_text("${info}" "加密算法：XChaCha20-Poly1305")
            endif()
            if(directory)
                expect_text("${info}" "目录：是")
                expect_text("${info}" "目录索引长度：0 字节")
            else()
                expect_text("${info}" "目录：否")
            endif()
            if(compressed)
                expect_text("${info}" "压缩：是")
                expect_text("${info}" "压缩算法：Zstandard")
            else()
                expect_text("${info}" "压缩：否")
            endif()
            expect_text("${info}" "认证状态：未验证")
            file(SHA256 "${path}" before)
            run_failure(sample "${path}" ${options})
            file(SHA256 "${path}" after)
            if(NOT before STREQUAL after)
                message(FATAL_ERROR "已有文件被覆盖")
            endif()
        endforeach()
    endforeach()
endforeach()

file(WRITE "${TEST_DIR}/invalid.fcry" "FCRX")
run_failure(info "${TEST_DIR}/invalid.fcry")
string(REPEAT "x" 124 invalid_tail)
file(WRITE "${TEST_DIR}/invalid.fcry" "FCRX${invalid_tail}")
run_failure(info "${TEST_DIR}/invalid.fcry")
run_failure(info "${TEST_DIR}/missing.fcry")
run_failure(sample "${TEST_DIR}/bad-option.fcry" --algorithm unsupported)
if(EXISTS "${TEST_DIR}/bad-option.fcry")
    message(FATAL_ERROR "非法选项创建了文件")
endif()

# info 只解释公开前缀，载荷的存在不代表认证成功。
file(APPEND "${path}" "payload")
run_success(info info "${path}")
expect_text("${info}" "载荷：存在")
expect_text("${info}" "认证状态：未验证")
