cmake_minimum_required(VERSION 3.24)
project(FileCryptBotanPoc LANGUAGES CXX)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
find_package(Botan 3 REQUIRED)
add_library(poc_crypto crypto.cpp)
target_compile_features(poc_crypto PUBLIC cxx_std_23)
set_target_properties(poc_crypto PROPERTIES CXX_EXTENSIONS OFF)
target_include_directories(poc_crypto PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
target_link_libraries(poc_crypto PUBLIC Botan::Botan)
add_executable(botan_poc tests.cpp)
target_link_libraries(botan_poc PRIVATE poc_crypto)
enable_testing()
add_test(NAME botan_poc COMMAND botan_poc)
