option(Zstd_USE_STATIC_LIBS "使用 Zstandard 静态库及其传递依赖" OFF)
find_package(PkgConfig QUIET)
if(Zstd_USE_STATIC_LIBS AND (UNIX OR MINGW))
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(PC_ZSTD REQUIRED libzstd)
elseif(PkgConfig_FOUND AND NOT Zstd_USE_STATIC_LIBS)
    pkg_check_modules(PC_ZSTD QUIET libzstd)
endif()
find_path(Zstd_INCLUDE_DIR zstd.h HINTS ${PC_ZSTD_INCLUDE_DIRS})
if(Zstd_USE_STATIC_LIBS AND (UNIX OR MINGW))
    set(_zstd_suffixes "${CMAKE_FIND_LIBRARY_SUFFIXES}")
    set(CMAKE_FIND_LIBRARY_SUFFIXES .a)
endif()
find_library(Zstd_LIBRARY NAMES zstd zstd_static libzstd HINTS ${PC_ZSTD_LIBRARY_DIRS})
if(Zstd_USE_STATIC_LIBS AND (UNIX OR MINGW))
    set(CMAKE_FIND_LIBRARY_SUFFIXES "${_zstd_suffixes}")
    if(Zstd_LIBRARY AND (NOT Zstd_LIBRARY MATCHES "\\.a$" OR Zstd_LIBRARY MATCHES "\\.dll\\.a$"))
        message(FATAL_ERROR "Zstd 静态发布需要 .a 库；请清除旧的 Zstd_LIBRARY 缓存")
    endif()
endif()
if(Zstd_INCLUDE_DIR)
    file(STRINGS "${Zstd_INCLUDE_DIR}/zstd.h" _zstd_version
        REGEX "^#define ZSTD_VERSION_(MAJOR|MINOR|RELEASE) +[0-9]+")
    foreach(_part MAJOR MINOR RELEASE)
        string(REGEX MATCH "ZSTD_VERSION_${_part} +([0-9]+)" _match "${_zstd_version}")
        set(_zstd_${_part} "${CMAKE_MATCH_1}")
    endforeach()
    set(Zstd_VERSION "${_zstd_MAJOR}.${_zstd_MINOR}.${_zstd_RELEASE}")
endif()
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Zstd REQUIRED_VARS Zstd_INCLUDE_DIR Zstd_LIBRARY VERSION_VAR Zstd_VERSION)
if(Zstd_FOUND AND NOT TARGET Zstd::Zstd)
    add_library(Zstd::Zstd UNKNOWN IMPORTED GLOBAL)
    set_target_properties(Zstd::Zstd PROPERTIES IMPORTED_LOCATION "${Zstd_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "${Zstd_INCLUDE_DIR}")
    if(Zstd_USE_STATIC_LIBS AND PC_ZSTD_FOUND)
        set(_zstd_dependencies ${PC_ZSTD_STATIC_LIBRARIES})
        list(REMOVE_ITEM _zstd_dependencies zstd)
        set_target_properties(Zstd::Zstd PROPERTIES
            INTERFACE_LINK_LIBRARIES "${_zstd_dependencies}"
            INTERFACE_LINK_DIRECTORIES "${PC_ZSTD_STATIC_LIBRARY_DIRS}"
            INTERFACE_LINK_OPTIONS "${PC_ZSTD_STATIC_LDFLAGS_OTHER}")
    endif()
endif()
